# Generated by Django 3.2.3 on 2021-05-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='subs_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subs_plan',
            field=models.CharField(default='No plan', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.plan'),
        ),
    ]
