# Generated by Django 3.2.3 on 2021-05-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210528_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.plan'),
        ),
    ]
