# Generated by Django 3.2.3 on 2021-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210528_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='validity',
            field=models.IntegerField(default=0),
        ),
    ]
