# Generated by Django 3.2.3 on 2021-05-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_plan_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subs_plan',
        ),
    ]
