# Generated by Django 3.2.3 on 2021-06-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_subs_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan_name',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
