# Generated by Django 3.2.3 on 2021-06-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210601_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('validity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.plan'),
        ),
    ]
